In [0]:
# 「Hello World」の表示
print('Hello World')

Hello World


In [0]:
a = 1
b = 2
c = a + b
print(a, b, c)

1 2 3


In [0]:
a = 11
s = 'aは10以上' if a>10 else  'aは10未満'
print(s)

aは10以上


In [0]:
text = '''1行目のテキスト。
2行目のテキスト。'''
print(text)

1行目のテキスト。
2行目のテキスト。


In [0]:
print('文字列' + 'の連結')

文字列の連結


In [0]:
print('答え = ' + str(100))

答え = 100


In [0]:
text = 'Hello World'
print(text[1:3])
print(text[:5])
print(text[6:])

el
Hello
World


In [0]:
a = 'Test'
b = 100
c = 3.14159

print('文字列 = {}'.format(a))
print('整数 = {}'.format(b))
print('浮動小数点 = {}'.format(c))
print('浮動小数点下2桁 = {:.2f}'.format(c))
print ('複数の変数 = {}, {}, {:.2f}'.format(a, b, c))

文字列 = Test
整数 = 100
浮動小数点 = 3.14159
浮動小数点下2桁 = 3.14
複数の変数 = Test, 100, 3.14


In [0]:
my_list = [1, 2, 3, 4]
print(my_list)
print(my_list[0])
print(my_list[1:3])

[1, 2, 3, 4]
1
[2, 3]


In [0]:
my_list = [1, 2, 3, 4]
my_list[0] = 10
print(my_list)
my_list[1:4] = [20, 30]
print(my_list)

[10, 2, 3, 4]
[10, 20, 30]


In [0]:
my_list = ['Apple', 'Cherry']
print(my_list)
my_list.append('Strawberry')
print(my_list)
del my_list[1]
print(my_list)
my_list.remove('Apple')
print(my_list)

['Apple', 'Cherry']
['Apple', 'Cherry', 'Strawberry']
['Apple', 'Strawberry']
['Strawberry']


In [0]:
print(list(range(10)))
print(list(range(1, 7)))
print(list(range(1, 10, 2)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6]
[1, 3, 5, 7, 9]


In [0]:
my_dic = {'Apple': 300, 'Cherry': 200, 'Strawberry': 3000}
print(my_dic['Apple'])

300


In [0]:
my_dic = {'Apple': 300, 'Cherry': 200, 'Strawberry': 3000}
my_dic['Apple'] = 400
print(my_dic)

{'Apple': 400, 'Cherry': 200, 'Strawberry': 3000}


In [0]:
my_dic = {'Apple' : 300}
print(my_dic)
my_dic['Cherry'] = 200
print(my_dic)
del my_dic['Apple']
print(my_dic)

{'Apple': 300}
{'Apple': 300, 'Cherry': 200}
{'Cherry': 200}


In [0]:
my_taple = (1, 2, 3, 4)
print(my_taple)
print(my_taple[0])
print(my_taple[1:3])

(1, 2, 3, 4)
1
(2, 3)


In [0]:
num = 5
if num >= 10:
    print('numが10以上') # 条件が成立
else:
    print('numが10未満') # 条件が未成立

numが10未満


In [0]:
num = 10
if num >= 5:
    print('numが5以上') # 1つ目の条件が成立
elif num >= 3:
    print('numが3以上') # 2つ目の条件が成立
else:
    print('numが3未満') # 条件が未成立

numが5以上


In [0]:
for n in [1, 2, 3]:
    print(n), # 繰り返し対象
    print(n*10) # 繰り返し対象

1
10
2
20
3
30


In [0]:
for n in range(5):
    print(n), # 繰り返し対象

0
1
2
3
4


In [0]:
i = 0
while i < 20:
    i += 1
    if i % 2 == 0:
        continue
    if i % 3 == 0:
        print(i)

3
9
15


In [0]:
for num, fruit in enumerate(['Apple', 'Cherry', 'Strawberry']):
    print('{}:{}'.format(num, fruit))

0:Apple
1:Cherry
2:Strawberry


In [0]:
my_list1 = []
for x in range(10):
    my_list1.append(x * 2)
print(my_list1)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [0]:
my_list2 = [x * 2 for x in range(10)]
print(my_list2)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [0]:
def radian(x):
    return x / 180 * 3.1415

for x in range(0, 360, 90):
    print('度: {}, ラジアン: {:.2f}'.format(x, radian(x)))

度: 0, ラジアン: 0.00
度: 90, ラジアン: 1.57
度: 180, ラジアン: 3.14
度: 270, ラジアン: 4.71


In [0]:
lambda_radian = (lambda x:x / 180 * 3.1415)

for x in range(0, 360, 90):
    print('度: {}, ラジアン: {:.2f}'.format(x, lambda_radian(x)))

度: 0, ラジアン: 0.00
度: 90, ラジアン: 1.57
度: 180, ラジアン: 3.14
度: 270, ラジアン: 4.71


In [0]:
class HelloClass:
    def __init__(self, msg):
        self.msg = msg

    def output(self):
        print(self.msg)

hello = HelloClass('Hello World')
hello.output()

Hello World


In [0]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [0]:
from numpy import array

a = array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
